all:
  hosts:
    minikube:
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  vars:
    # Kubernetes configuration
    kubeconfig_path: "~/.kube/config"
    namespace: medical-chatbot
    
    # Application configuration
    app_name: medical-chatbot
    docker_registry: manasmann
    
    # Resource limits
    backend_replicas: 1
    frontend_replicas: 2