---
all:
  children:
    kubernetes:
      children:
        masters:
          hosts:
            minikube:
              ansible_host: 192.168.49.2  # Your Minikube IP
              ansible_user: docker  # User inside Minikube VM
