apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: expense-tracker
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  POSTGRES_DB: ZXhwZW5zZV90cmFja2Vy  # expense_tracker
  VAULT_TOKEN: cm9vdA==  # root
