apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: medical-chatbot
data:
  MONGODB_URL: "mongodb://host.minikube.internal:27017/medicaldb"
  VAULT_URL: "http://host.minikube.internal:8200"
  VAULT_TOKEN: "hvs.NI7tB3V1PTeodrex7PVHd7UE"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: medical-chatbot
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} - %{LOGLEVEL:log_level} - %{WORD:component}( - %{WORD:action})?( - %{DATA:details})?" }
      }
      
      # Parse HTTP logs 
      if [component] == "HTTP" {
        grok {
          match => { "details" => "%{WORD:method} %{URIPATHPARAM:path} - Status: %{NUMBER:status_code} - Time: %{NUMBER:response_time}ms - IP: %{IP:client_ip}" }
        }
      }
      
      # Parse AUTH logs
      if [component] == "AUTH" {
        grok {
          match => { "details" => "User: %{USERNAME:username} - IP: %{IP:client_ip}( - Agent: %{GREEDYDATA:user_agent})?" }
        }
      }
      
      date {
        match => [ "timestamp", "yyyy-MM-dd HH:mm:ss,SSS" ]
        target => "@timestamp"
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "medical-chatbot-logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: medical-chatbot
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /app/logs/app.log
      multiline:
        pattern: '^\d{4}-\d{2}-\d{2}'
        negate: true
        match: after
    
    output.logstash:
      hosts: ["logstash:5044"]
    
    logging.level: info
