apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: medical-chatbot
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: medical-chatbot
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 2Gi
