apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.6.0
        ports:
        - containerPort: 5044
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: expense-tracker
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    filter {
      # Add filters as needed
    }
    
    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "expense-tracker-%{+yyyy.MM.dd}"
      }
    }
