apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.14.3
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: VAULT_TOKEN
        - name: VAULT_ADDR
          value: "http://0.0.0.0:8200"
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/data
        - name: vault-init
          mountPath: /vault-init.sh
          subPath: vault-init.sh
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-pvc
      - name: vault-init
        configMap:
          name: vault-init-script
          defaultMode: 0777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-init-script
  namespace: expense-tracker
data:
  vault-init.sh: |
    #!/bin/sh
    vault secrets enable -path=secret kv-v2
    echo "Vault initialized and configured."
