- name: Apply all Kubernetes manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    - "../../../../kubernetes/namespace.yaml"
    - "../../../../kubernetes/storage.yaml"
    - "../../../../kubernetes/config.yaml"
    - "../../../../kubernetes/services.yaml"
    - "../../../../kubernetes/deployments.yaml"
    - "../../../../kubernetes/hpa.yaml"
